import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { Rating } from './Rating';
import { ImageWithFallback } from './figma/ImageWithFallback';
export const BookCard = React.memo(({ book }) => {
    return (_jsxs(motion.div, { whileHover: { y: -8 }, className: "group flex flex-col gap-3 w-full", children: [_jsxs(Link, { to: `/book/${book.id}`, className: "relative aspect-[2/3] overflow-hidden rounded-xl bg-secondary border border-base", children: [_jsx(ImageWithFallback, { src: book.cover, alt: book.title, className: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-4", children: _jsx("button", { className: "w-full py-2 bg-accent text-white rounded-lg text-sm font-medium shadow-lg", children: "\u0427\u0438\u0442\u0430\u0442\u044C" }) })] }), _jsxs("div", { className: "flex flex-col gap-1", children: [_jsxs("div", { className: "flex items-center justify-between gap-2", children: [_jsx(Link, { to: `/book/${book.id}`, className: "text-sm font-semibold text-primary line-clamp-1 hover:text-accent transition-colors", children: book.title }), _jsx("span", { className: "text-[11px] font-medium text-secondary", children: book.year })] }), _jsx("p", { className: "text-xs text-secondary", children: book.author }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx(Rating, { rating: book.rating, size: 12 }), _jsxs("span", { className: "text-[10px] text-secondary", children: ["(", book.reviewsCount, ")"] })] }), _jsx("div", { className: "flex flex-wrap gap-1 mt-2", children: book.tags.slice(0, 2).map(tag => (_jsx("span", { className: "px-2 py-0.5 bg-secondary text-secondary text-[10px] rounded-full border border-base", children: tag }, tag))) })] })] }));
});
